# Site settings
title: Simon Goring
email: simon.j.goring@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Building tools to facilitate outreach and support diversity in the biogeosciences.
baseurl: ""
url: "http://goring.org"
twitter_username: sjgoring
github_username:  SimonGoring

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

collections:
  resources:
    output: true
  cv:
    output: true

plugins_dir:
  - jekyll-sitemap
  - jekyll-seo-tag
